name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # deploy only when main is updated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # ensures GITHUB_TOKEN is available

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build project for GitHub Pages
      - name: Build for GitHub Pages
        run: npm run buildgit

      # Step 4.5: Print npm log files if they exist
      - name: Print npm log files
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log

      # Step 6: Configure git user (needed for commits)
      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Remove gh-pages cache
        run: rm -rf node_modules/.cache/gh-pages

      # Step 6: Deploy to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          user_name: github-actions
          user_email: github-actions@github.com
